### ISSUE TITLE
Changing Version of EF Core Stops Visual Studio 2017 to stop working, closes Visual Studio

### ISSUE THREAD

**Issue by MG1093** [msawczyn/EFDesigner#27] opened 2018-10-10 16:59 UTC
Changing Version of EF Core Stops Visual Studio 2017 to stop working, closes Visual Studio

**Comment by msawczyn** [comment] 2018-10-10 17:59
I can't replicate that problem. Can you please provide steps and, if possible, the error messages (if any) you see?

Thanks.

**Comment by xemage** [comment] 2018-10-11 07:37
I think I have the same issue here and can reproduce it.
- Create a new project of type `Class Library (.NET Core)`
- Add new item of type `EFDesigner`
- Open the `.efmodel` file
- Change `Entity Framework Version` from `EF6` to `EFCore`
- Try to change `Entity Framework Package Version`

This causes a crash of Visual Studio here.
If you tell me where I can find additional information like a crash report I could forward it to you.

**Comment by msawczyn** [comment] 2018-10-12 18:59
Thanks for the repro steps. Unfortunately, when I try that it doesn't crash :-( The version I changed to was initially was 2.1.4, but changing to any version worked fine.

Could you try the latest build and see if the problem still exists? You can get it from https://github.com/msawczyn/EFDesigner/raw/master/dist/Sawczyn.EFDesigner.EFModel.DslPackage.vsix - it's v1.2.6.12

For crash messages, you'd need to [turn on logging for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe?view=vs-2017). Any errors should be there. But hopefully the reason I can't repro is that something fixed it in the latest codebase ... if so, I'll push that out as quickly as possible.

**Comment by msawczyn** [comment] 2018-10-22 11:32
@MG1093 and @xemage - any chance you've tried the 1.2.6.12 build? Since I can't reproduce the problem with that build, I'd be interested if either of you still see the issue. If not, I'll close this.

Thanks.

**Closed** 2018-10-24 11:30 UTC
Labels: no repro
