### ISSUE TITLE
Upgrade entity framework visual editor to latest version, now EF Model Diagrams disabled

### ISSUE THREAD

**Issue by Relki** [msawczyn/EFDesigner#333] opened 2022-12-31 06:42 UTC
Upgraded visual studio 2022 to latest version and have latest Visual Entity Framework Editor, and today. Today, I went to add some new tables to my model, and all the components were missing in the toolbox for EF Model Diagrams. I clicked Show ALL in the toolbox, and I can see that all the EF Model Diagrams components are disabled. Don't know what to do now. I'll try uninstalling the extension and reinstalling.

![image](https://user-images.githubusercontent.com/45949455/210127835-1c2064f8-c755-48c3-81a9-173b0fe919cc.png)

VS 2022 version: 17.4.3
EFDesigner extension version: 4.2.13

**Comment by Relki** [comment] 2023-01-02 18:47
Related to https://github.com/msawczyn/EFDesigner/issues/323

**Comment by msawczyn** [comment] 2023-01-04 13:36
Duplicate of https://github.com/msawczyn/EFDesigner/issues/323

**Closed** 2023-01-04 13:36 UTC
Labels: duplicate
