### ISSUE TITLE
AutoProperty after update

### ISSUE THREAD

**Issue by VioletS** [msawczyn/EFDesigner#109] opened 2019-10-15 09:39 UTC
After updating to 1.3.0.6, and trying clean with 1.3.0.7,
I noticed existing properties are read in with AutoProperty false.
With your fix in 1.3.0.7 this would no longer generate new columns in the database (leading to a breaking change) but I would still think they should be read as true by default, as that matches previous code generation.

**Comment by msawczyn** [comment] 2019-10-16 05:33
That was an unfortunate side effect of the bad code merge that led to the 1.3.0.6 problem. The `AutoProperty` values for entities in your model may have been set to `true` and, when you saved the model, those got persisted. It's been fixed and will be back to its old behavior in the next release.

You can check to see if the global edit was done by opening the .efmodel file as text (it's just XML) and searching for `autoProperty`. The quick fix is to simply remove the `autoProperty='true'` attributes from the file and save it again. 

Sorry for putting you (and others) through this. 1.3.0.6 was just an altogether bad version.

**Comment by VioletS** [comment] 2019-10-16 05:53
I'd have thought it was fixed from your comments, yes. 
However, when I load back in the old version without any mention of autoproperty,
make no changes and save again in the editor, I get a popup: "Value cannot be null. Parameter name: input." Then looking at the changed file, autoproperty has still been added as false.

**Comment by msawczyn** [comment] 2019-10-16 11:12
Hmm. If you could try something, there's a nightly build of 1.3.0.8 at https://github.com/msawczyn/EFDesigner/blob/v1.3.0.8/dist/Sawczyn.EFDesigner.EFModel.DslPackage.vsix that I used to test. Would you be willing to install and see if you can replicate the problem with that build, it would tell me a lot. Hopefully you can't reproduce it with that codebase but, if you can, I would next ask for a minimal repro file so I could debug into it.

Thanks for all your help.

**Comment by VioletS** [comment] 2019-10-17 07:42
The nightly no longer pops up the error, but the autoproperty=false is still added when upgrading the tool from 1.3.0.4 to 1.3.0.8. 
From your comments to remove the "=true" I gather this is intentional behavior.
False is your new code option with backing field, true is old behavior.
I have manually set them all to true, so the generated code has no changes and matches previously committed code.

**Comment by msawczyn** [comment] 2019-10-17 12:33
Hmm. Let me look further. We've added a property at the class level to default an attribute's `AutoProperty` setting (still working on updating the documentation for that), and there may be something going on there. I'll dig into it more. Thanks again.

**Comment by msawczyn** [comment] 2019-10-20 08:25
I've verified that current behavior is:
- entity default value for `AutoProperty Default` is `true`
- attribute default for `AutoProperty` honors entity `AutoProperty Default` setting (but can be overridden)

I'm going to close this now but if you don't see this behavior in 1.3.0.8 onward, please feel free to reopen.

**Closed** 2019-10-20 08:26 UTC
Labels: question
