### ISSUE TITLE
Required string identity property is not present in the constructor

### ISSUE THREAD

**Issue by Cyclonit** [msawczyn/EFDesigner#93] opened 2019-08-23 20:00 UTC
Hi,

I have a simple class, using a string property as Identity. The following properties are set in the designer:
- Required: True
- Column Type: default
- Identity Type: manual
- Indexed: True
- Indexed Unique: True
- Is Identity: True

Given that the identity type is set to manual, I am expecting it to show up in the generated Constructor, such that an identity can be assigned when an instance of the class is being generated. The constructor however, does not contain this property. The create(...) method does not have the property either.

Is this working as intended? If so: Why?

**Comment by msawczyn** [comment] 2019-08-25 21:26
Hmm. Certainly not as intended. I'll look into it. Thanks!

**Comment by msawczyn** [comment] 2019-09-09 16:28
This fix is in 1.3.0.5. Thanks for reporting it!

**Comment by Cyclonit** [comment] 2019-09-10 19:47
Thank you very much!

**Closed** 2019-09-30 11:29 UTC
Labels: fixed
