### ISSUE TITLE
EF6 Many to Many Relation within same Entity leads to Exception

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#162] opened 2020-03-26 16:59 UTC
Hello Michael,

I'm running into an issue when I try to create a many to many relation (using EF 6) within the same entity.

When I run the attached example project ([EFDesignerTest.zip](https://github.com/msawczyn/EFDesigner/files/4388589/EFDesignerTest.zip)) I get this exception:

> An unhandled exception of type 'System.Data.Entity.ModelConfiguration.ModelValidationException' occurred in EntityFramework.dll
One or more validation errors were detected during model generation:
Keyword_Id: Name: Each property name in a type must be unique. Property name 'Keyword_Id' is already defined.
KeywordKeyword: EntityType: EntitySet 'KeywordKeyword' is based on type 'KeywordKeyword' that has no keys defined.

What am I doing wrong here?
Is it not possible to create such a many to many relation with EFDesigner within the same entity?

Thanks a lot for your support in advance
Andreas

P. S.: Tested with version v1.3.0.12.

**Comment by ab-tools** [comment] 2020-03-26 17:18
I would prefer to stay with v1.3.0.12 for now, but I did a quick test with v2.0.0.1 with the same example project and here the code generations fails altogether:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Compiling transformation: The name 'SpatialTypes' does not exist in the current context	Miscellaneous Files	c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\pejz322l.vi1\TextTemplates\EF6Designer.ttinclude	386

**Comment by msawczyn** [comment] 2020-03-27 02:28
I can't reproduce the problem with the sample project you sent in 2.0.0.2. The issue you saw with 2.0.0.1 was a known problem that got fixed in the next build ... it's still pre-release and some of the bugs still need shaking out.

**Comment by ab-tools** [comment] 2020-03-27 09:15
Thanks for your quick reply, Michael!

Just to confirm:
You also do not see the original problem mentioned in my first message of this issue here with 2.0.0.2 anymore?

Where do I get the Visual Studio installer for 2.0.0.2 from by the way?

The latest version I can find is this here from the source:
https://github.com/msawczyn/EFDesigner/blob/master/dist/Sawczyn.EFDesigner.EFModel.DslPackage.vsix

I've tried with that, but still see even the same "Error Compiling transformation" as from my comment above (so I can try to reproduce the original problem of this issue as it doesn't compile in the first place).

Thanks
Andreas

**Comment by msawczyn** [comment] 2020-03-27 10:34
I can't repro the first issue in 2.0.0.2 either, so please give it a try. The pre-release is available at https://github.com/msawczyn/EFDesigner/releases/tag/v2.0.0.2

**Comment by ab-tools** [comment] 2020-03-27 11:43
Hello Michael,

I'm a bit confused why things seem to work fine for me with the same version, but do not for me. ;-)

So I tried v2.0.0.2 from the link you provided with the sample project from above and regenerated the model. First exception I immediately got was this here:
![image](https://user-images.githubusercontent.com/1347603/77752425-d2bf2880-7027-11ea-9c02-23e7f3e02d47.png)

So there is obviously a typo in this line of that file (";" at the wrong place) which I fixed.
Afterwards compilation worked.

Then I did run the example project and immediately get the same exception as in my very first post also with v2.0.0.2:

> System.Data.Entity.ModelConfiguration.ModelValidationException: 'One or more validation errors were detected during model generation:
Keyword_Property1: Name: Each property name in a type must be unique. Property name 'Keyword_Property1' is already defined.
KeywordKeyword: EntityType: EntitySet 'KeywordKeyword' is based on type 'KeywordKeyword' that has no keys defined.

Here is an updated version of the example project compiled with v2.0.0.2: 
[EFDesignerTest.zip](https://github.com/msawczyn/EFDesigner/files/4393249/EFDesignerTest.zip)

Do you not get the ModelValidationException above when you run that against a Microsoft SQL Server?

Thanks again for your support on this
Andreas

**Comment by msawczyn** [comment] 2020-03-27 11:55
Yes, quite odd ... that typo was there last night but fixed in the version I just pushed up. I'll take a look; hopefully I didn't do something stupid like push up the wrong build.

Going to try the updated version you just posted.

**Comment by msawczyn** [comment] 2020-03-27 12:08
Darn. Yup - Line 518 in EFDesigner.ttinclude should be
```
            Output($"return new {modelClass.Name}();");
```
Not sure how that happened. My apologies.

**Comment by ab-tools** [comment] 2020-03-27 12:12
No worries, Michael, that can easily happen!

But the strange thing is that even if I fix this line manually I still do get the original "ModelValidationException" like I mentioned above.

That's the same exception I also get with v1.3.0.12.

Do you see this exception happening if you try my latest example project?

**Comment by msawczyn** [comment] 2020-03-27 12:20
Interesting. I didn't get the point that the error occurred during `update-database`, so didn't take it that far. When I did so, I saw the problem.

Changing the line in `DbModel.dgen.cs` on line 126 from
```
.Map(x => { x.ToTable("Keyword_x_LinkedKeyword"); x.MapLeftKey("Keyword_Property1"); x.MapRightKey("Keyword_Property1"); });
```
to
```
.Map(x => { x.ToTable("Keyword_x_LinkedKeyword"); x.MapLeftKey("Keyword_Property1A"); x.MapRightKey("Keyword_Property1B"); });
```
(or something like it, as long as the left and right keys are different) fixes the issue. Now I need to find out why that hasn't appeared before, because I know both I and thousands of others have created self-associations that worked in the past.

Thanks for the update!

**Comment by ab-tools** [comment] 2020-03-27 12:26
Great that you could reproduce it now - thanks a lot for your efforts! :-)

I see exactly the same issue with v1.3.0.12, so it's not related to your major changes in v2.

If that's still possible I would really appreciate a fix in the v1.3 branch that I can postpone the upgrade to v2 a bit as this does not seem to be very stable yet (also with no real upgrade path available yet like mentioned in #161).

Please let me know in case I should test anything else or you need more info!

Appreciating your efforts a lot
Andreas

**Comment by msawczyn** [comment] 2020-03-28 00:48
Since the changes are in the .ttinclude, there isn't anything to do in the extension itself.

In `EF6Designer.ttinclude`, search for the word `sourceMap`. It will be in two blocks of code, both involved in outputting a `Map` call, around lines 500 and 615.

You will want to change
```
string tableMap = string.IsNullOrEmpty(association.JoinTableName) ? $"{association.Source.Name}_x_{association.TargetPropertyName}" : association.JoinTableName;
string sourceMap = string.Join(", ", association.Source.AllIdentityAttributeNames.Select(n => $@"""{association.Source.Name}_{n}""").ToList());
string targetMap = string.Join(", ", association.Target.AllIdentityAttributeNames.Select(n => $@"""{association.Target.Name}_{n}""").ToList());
```
to
```
string tableMap = string.IsNullOrEmpty(association.JoinTableName) ? $"{association.Source.Name}_x_{association.TargetPropertyName}" : association.JoinTableName;
string suffix1 = association.Source == association.Target ? "A" : "";
string suffix2 = association.Source == association.Target ? "B" : "";
string sourceMap = string.Join(", ", association.Source.AllIdentityAttributeNames.Select(n => $@"""{association.Source.Name}_{n}{suffix1}""").ToList());
string targetMap = string.Join(", ", association.Target.AllIdentityAttributeNames.Select(n => $@"""{association.Target.Name}_{n}{suffix2}""").ToList());
```
to add a change to the column names when the source and target are the same class.

**Comment by ab-tools** [comment] 2020-03-28 18:31
Thanks, Michael, but if I search in the file `EF6Designer.ttinclude` ([EF6Designer.zip](https://github.com/msawczyn/EFDesigner/files/4397639/EF6Designer.zip)) for the word `sourceMap` I do not find a single hit.

Any idea where I need to fix/change this?

Please note the file is from version v1.3.0.12 as I don't see the possibility to upgrade to v2 yet.

Thanks a again a lot for your support on this
Andreas

**Comment by msawczyn** [comment] 2020-03-29 15:09
The goal is to ensure that, in the shadow join tables, the column names are always unique. That's a problem when there's a self many-to-many join, as the heuristic creating the column names comes up with the same answer for both sides of the join.

The quick answer is to just ensure the names are unique no matter what: add a prefix or suffix to the column names. So, where we have
```
segments.Add("Map(x => { " + $@"x.ToTable(""{association.Source.Name}_x_{association.TargetPropertyName}""); " + $@"x.MapLeftKey(""{association.Source.Name}_{association.Source.AllAttributes.FirstOrDefault(a => a.IsIdentity)?.Name}""); " + $@"x.MapRightKey(""{association.Target.Name}_{association.Target.AllAttributes.FirstOrDefault(a => a.IsIdentity)?.Name}""); " + "})");
```
it becomes
```
segments.Add("Map(x => { " + $@"x.ToTable(""{association.Source.Name}_x_{association.TargetPropertyName}""); " + $@"x.MapLeftKey(""L{association.Source.Name}_{association.Source.AllAttributes.FirstOrDefault(a => a.IsIdentity)?.Name}""); " + $@"x.MapRightKey(""R{association.Target.Name}_{association.Target.AllAttributes.FirstOrDefault(a => a.IsIdentity)?.Name}""); " + "})");
```
or somesuch, as long at we're sure that, no matter what the values of the interpolated variables used to generate the MapLeftKey and MapRightKey calls, the parameters will be different.

Note that there are 4 places in that template where that kind of change needs to happen: lines 464, 468, 570 and 574.

Note that this will change the column names for _all_ shadow join tables, whether they need it or not, but it's the simplest solution. To be more selective, you should do something similar to the prior discussion where you'd check to see if the source and target referred to the same class and do the modification only in that case.

But this should get you going again.

**Comment by ab-tools** [comment] 2020-03-29 16:02
Thanks a lot for your explanations, Michael!

To be honest I'm a bit worried that messing around with this will lead to issues when I then update to your next official release again.

I see that you are very actively working on this project right now, so maybe I just wait a few more days till you have this fixed in v2, this is stable enough and the migration problem (#161) is solved that I can directly upgrade to that.

Thanks a lot for your efforts again
Andreas

**Comment by msawczyn** [comment] 2020-03-30 10:48
#161 has been solved for a few pre-releases now. You can always see the state of the issues in the tags attached to the issue reports, or on the project's [Kanban board](https://github.com/msawczyn/EFDesigner/projects/2).

You're taking a good approach; always be wary of pre-release versions...that's why they're tagged that way :-)

**Closed** 2020-04-11 17:15 UTC
Labels: bug, fixed
