### ISSUE TITLE
Some Issue in design surface

### ISSUE THREAD

**Issue by y976362357** [msawczyn/EFDesigner#86] opened 2019-07-31 08:08 UTC
hi, i found some issue in design surface.

1. can't select the ef package version

![a](https://user-images.githubusercontent.com/15923358/62193310-12a31280-b3aa-11e9-8a5b-505ef510b7b9.png)

why cause this? 
it depends on some urls i can't visit?
---

2. generated code error

i have a entity named **Sample**.

then using **add properties via code**  add the following code with initial value default for Propertity  Name

`public Int32 Id!;
public String Name = "default";`
---

generated code like below:
double quotation marks with the **default** value
---
public partial class Sample
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Sample()
      {
         Name = ""default"";  //double quotation marks

         Init();
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get; private set; }

      /// <summary>
      /// Required, Default value = ""default""
      /// </summary>
      [Required]
      public string Name { get; set; }

   }

---
3.Adding Properties via Code can't set min length of string

when i type the code in add properties as code like below.

`public Int32 Id!;
public String[10-40] Name;`
---
then save and open the add properties via code again.

it show the code like below
`
public Int32 Id!;
public String[40] Name;`

**Comment by msawczyn** [comment] 2019-08-07 11:12
1. It could indeed be that you can't reach the resource on the internet. It's getting the list of available versions from the Nuget server that you have configured in your Visual Studio installation.

2. I haven't seen that happen before, but I'll certainly look into it. Could you please add that as an issue in Github so it doesn't fall through the cracks?

3. Same as #2 

Thanks for letting me know about these.

**Comment by msawczyn** [comment] 2019-08-12 10:20
2) and 3) will be fixed in the next release. I can't reproduce your first issue, though.

For future reference, please report issues separately, since they may be solved separately. It just makes it easier for developers to both track the issues and to find how they were fixed historically. Thanks.

**Comment by mmarinchenko** [comment] 2019-08-19 10:08
1. This doesn't work for me too (VS 2017).

NuGet API URL is actually reachable on the machine: `https://api-v2v3search-0.nuget.org/query?q=Microsoft.EntityFrameworkCore&prerelease=false`.

JSON with packages data is returned. Tested in Chrome and Edge.

**Closed** 2019-09-30 11:29 UTC
Labels: fixed, no repro, question

**Comment by mmarinchenko** [comment] 2019-11-12 06:54
> hi, i found some issue in design surface.
> 
> 1. can't select the ef package version
----
> 1. This doesn't work for me too (VS 2017).
> 
> NuGet API URL is actually reachable on the machine: `https://api-v2v3search-0.nuget.org/query?q=Microsoft.EntityFrameworkCore&prerelease=false`.
> 
> JSON with packages data is returned. Tested in Chrome and Edge.

Now it's working (as of v1.3.0.10)! Thanks :)
