### ISSUE TITLE
Importing a model from assembly and string length

### ISSUE THREAD

**Issue by alprinias** [msawczyn/EFDesigner#241] opened 2020-11-30 07:45 UTC
During importing a model from an assembly:
The string properties of my assemply-imported classes had a [StringLength(nn)] attribute, which was not honored by the importing process, leaving all of them with maxLength="0" in the xml (and with yellow exclamation mark triangles in the designer). A suggestion would be to set the maxLength during the import based on such an attribute. If possible, of course.

**Comment by msawczyn** [comment] 2020-12-04 13:27
Duplicate of #242 - fixed in v3.0.1. Closing.

**Closed by msawczyn** 2020-12-04 13:27 UTC
Labels: enhancement
